# Delong comments: the following codes is generated by ChatGPT 3.5
#' Multiply two numbers
#'
#' @param x First number
#' @param y Second number
#' @return The product of x and y
#' @examples
#' multiply(3, 4)
#' multiply(0.5, 2)
multiply <- function(x, y) {
  return(x * y)
}
